export const typeColors: Record<string, string> = {
  fire: 'orange',
  water: 'blue',
  grass: 'green',
  electric: 'yellow',
  ice: 'lightblue',
  fighting: 'brown',
  poison: 'purple',
  ground: 'tan',
  flying: 'skyblue',
  psychic: 'pink',
  bug: 'limegreen',
  rock: 'gray',
  ghost: 'indigo',
  dragon: 'gold',
  dark: 'black',
  steel: 'silver',
  fairy: 'pink',
  normal: 'beige',
};
